mydemosite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from gallery import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^albums/$', views.AlbumListView.as_view(), name='albums'),
    url(r'^album/(?P<pk>\d+)$', views.AlbumDetailView.as_view(), name='album-detail'),
    url(r'^photos/$', views.PhotoListView.as_view(), name='photos'),
    url(r'^photo/(?P<pk>\d+)$', views.PhotoDetailView.as_view(), name='photo-detail'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gallery/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from imagekit.models import ImageSpecField
from pilkit.processors import ResizeToFit
# Create your models here.

class Album(models.Model):
    """
    Model representing an Album.
    """
    title = models.CharField(max_length=200)
    summary = models.TextField(max_length=1000, help_text="Enter a brief description of the Album")
    cover = models.ImageField(upload_to='covers/',null=True, blank=True)
    cover_thumbnail = ImageSpecField(source='cover',
                                      processors=[ResizeToFit(400, 300)],
                                      format='JPEG',
                                      options={'quality': 100})
    cover_thumbnail_small = ImageSpecField(source='cover',
                                      processors=[ResizeToFit(200, 150)],
                                      format='JPEG',
                                      options={'quality': 80})
    created = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    modified = models.DateTimeField(auto_now=True, blank=True, null=True)

    class Meta:
        ordering = ['created']

    def get_absolute_url(self):
        """
        Returns the url to access a particular album instance.
        """
        return reverse('album-detail', args=[str(self.id)])

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.title

class Photo(models.Model):
    """
    Model representing a Photo.
    """
    title = models.CharField(max_length=200)
    album = models.ForeignKey('Album', on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=1000, help_text="Enter a brief description of the Photo")
    picture = models.ImageField(upload_to='photos/',null=True, blank=True)
    picture_thumbnail = ImageSpecField(source='picture',
                                      processors=[ResizeToFit(400, 300)],
                                      format='JPEG',
                                      options={'quality': 100})
    picture_thumbnail_small = ImageSpecField(source='picture',
                                      processors=[ResizeToFit(200, 150)],
                                      format='JPEG',
                                      options={'quality': 80})
    created = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    modified = models.DateTimeField(auto_now=True, blank=True, null=True)

    def get_absolute_url(self):
        """
        Returns the url to access a particular photo instance.
        """
        return reverse('photo-detail', args=[str(self.id)])

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.title

gallery/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.views import generic
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Album, Photo

def home(request):
    """
    View function for home page of site.
    """
    # Number of visits to this view, as counted in the session variable.
    num_visits=request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits+1
    # Latest picture List
    latest_picture_list = Photo.objects.order_by('-created')[:15]
    # Render the HTML template home.html with the data in the context variable
    return render(
        request,
        'home.html',
        context={
            'num_visits':num_visits,
            'latest_picture_list':latest_picture_list,
        }
    )

class AlbumListView(generic.ListView):
    """
    Generic class-based list view for a list of albums.
    """
    model = Album
    paginate_by = 8

class AlbumDetailView(generic.DetailView):
    """
    Generic class-based detail view for an album.
    """
    model = Album
    #login_url = '/login/'

    def album_detail_view(request,pk):
        try:
            album_id=Album.objects.get(pk=pk)
        except Album.DoesNotExist:
            raise Http404("Album does not exist")

        return render(
            request,
            'album_detail.html',
            context={'album':album_id,}
            )

class PhotoListView(generic.ListView):
    """
    Generic class-based list view for a list of photos.
    """
    model = Photo
    paginate_by = 8


class PhotoDetailView(generic.DetailView):
    """
    Generic class-based detail view for a photo.
    """
    model = Photo

def photo_detail_view(request,pk):
    try:
        photo_id=Photo.objects.get(pk=pk)
    except Photo.DoesNotExist:
        raise Http404("Photo does not exist")
        photo_id=get_object_or_404(Photo, pk=pk)

    return render(
        request,
        'photo_detail.html',
        context={'photo':photo_id,}
    )

templates/base.html
{% load static %}<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="{% static 'brand/favicon.ico' %}">

    <title>OFF Gallery</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/carousel.css' %}" rel="stylesheet">
  </head>

  <body>

    <header>
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
              <h4 class="text-white">About</h4>
              <p class="text-muted">
                '{{ settings.NAVBAR_QUOTE }}'
              </p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              <h4 class="text-white">Contact</h4>
              <ul class="list-unstyled">
                <li><a href="#" class="text-white">Follow on Twitter</a></li>
                <li><a href="#" class="text-white">Like on Facebook</a></li>
                <li><a href="mailto:{{ settings.SITE_EMAIL }}" class="text-white">Email me</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container d-flex justify-content-between">
          <a href="{% url 'home' %}" class="navbar-brand d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
            <strong>Gallery</strong>
          </a>

          <a href="{% url 'albums' %}" class="navbar-brand d-flex align-items-center">
            <strong>OFF Albums</strong>
          </a>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header>

    {% block content %}
    {% endblock %}

    <footer class="text-muted">
      <div class="container">
        <p class="float-right">
          <a href="#">Back to top</a>
        </p>
        <p>Designed and built by &copy; 2019 <a href="https://gitlab.com/offtechnologies/django-demo">offtechnologies</a></p>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/holder/2.9.4/holder.min.js" integrity="sha256-ifihHN6L/pNU1ZQikrAb7CnyMBvisKG3SUAab0F3kVU=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.css" integrity="sha256-HAaDW5o2+LelybUhfuk0Zh2Vdk8Y2W2UeKmbaXhalfA=" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.min.js" integrity="sha256-Y1rRlwTzT5K5hhCBfAFWABD4cU13QGuRN6P5apfWzVs=" crossorigin="anonymous"></script>

    <script>
    $(document).on('click', '[data-toggle="lightbox"]', function(event) {
                    event.preventDefault();
                    $(this).ekkoLightbox();
                });
    </script>
  </body>
</html>

templates/gallery/album_detail.html
{% extends "base.html" %}

{% block content %}

<section>

<div class="album py-5 bg-light">
      <div class="container">
        <h4 class="mt-0">{{ album.title }}</h4>
        <h6 class="mt-0 text-muted">{{ album.summary }}</h6>
        <h6 class="mt-0 text-muted">Last updated: {{ album.modified|date:"M Y" }}</h6>
          <p></p>
            <div class="row">
              {% if album.photo_set %}
              {% for photo in album.photo_set.all %}
                <div class="col-md-4">
                  <div class="card mb-4 shadow-sm">
                    <a href="{{ photo.picture.url }}"
                       data-toggle="lightbox"
                       data-gallery="{{ album.title }}"
                       data-title="{{ photo.title }}"
                       data-footer="{{ photo.summary }}">
                       <img class="card-img-top" src="{{ photo.picture_thumbnail.url }}" alt="{{ photo.title }}" >
                    </a>
                    <!-- Placed here for ref ...
                    <div class="card-body">
                      <h6 class="card-title">{{ photo.title }}</h6>
                      <p class="card-text">{{ photo.summary }} </p>
                      <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                          <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                        </div>
                        <small class="text-muted">{{ album.created|date:"d M Y" }}</small>
                      </div>
                    </div>
                    -->
                  </div>
                </div>
              {% endfor %}
              {% else %}
                  <p>There are no albums available...</p>
              {% endif %}
            </div>
      </div>
</div>

</section>

{% endblock %}

templates/gallery/album_list.html
{% extends "base.html" %}

{% block content %}

<section>

<div class="album py-5 bg-light">
      <div class="container">
            <div class="row">
              {% if album_list %}
              {% for album in album_list %}
                <div class="col-md-4">
                  <div class="card mb-4 shadow-sm">
                    <a href="{{ album.get_absolute_url }}">
                      <img class="card-img-top" src="{{ album.cover_thumbnail.url }}" alt="{{ album.title }}" >
                    </a>
                    <div class="card-body">
                      <h6 class="card-title">{{ album.title }}</h6>
                      <p class="card-text">{{ album.summary }} </p>
                      <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                          <a href="{{ album.get_absolute_url }}">
                          <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                        </div>
                        <small class="text-muted">{{ album.created|date:"d M Y" }}</small>
                      </div>
                    </div>
                  </div>
                </div>
              {% endfor %}
              {% else %}
                  <p>There are no albums available...</p>
              {% endif %}
            </div>
      </div>
</div>

</section>

{% endblock %}

templates/home.html
{% extends 'base.html' %} {% load random_image %}

{% block content %}

<main role="main">

  <section class="jumbotron text-center">
    <div class="container">

      <h1 class="jumbotron-heading">{{ settings.JUMBOTRON_HEADING }}</h1>
      <p class="lead text-muted">
        '{{ settings.JUMBOTRON_QUOTE }}'
      </p>
      <p>
        <a href="{% url 'albums' %}" class="btn btn-primary my-2">More</a>
      </p>

      <div id="carouselSlidesFade" class="carousel slide carousel-fade" data-ride="carousel">
        <div class="carousel-inner">
        {% for photo in latest_picture_list|slice:":15" %}
            {% if forloop.first %}
              <div class="carousel-item active">
                <img class="d-block w-100" src="{{ photo.picture.url }}" alt="{{ photo.title }}">
              </div>
            {% else %}
              <div class="carousel-item">
                <img class="d-block w-100" src="{{ photo.picture.url }}" alt="{{ photo.title }}">
              </div>
            {% endif %}
        {% endfor %}
        </div>
      </div>

    </div>
  </section>
</main>

{% endblock %}